LOAD DATA LOCAL INFILE 'Item_uniq.dat' INTO TABLE Item
FIELDS TERMINATED BY "|*|";

LOAD DATA LOCAL INFILE 'ItemCategory_uniq.dat' INTO TABLE ItemCategory
FIELDS TERMINATED BY "|*|";

LOAD DATA LOCAL INFILE 'Bid_uniq.dat' INTO TABLE Bid
FIELDS TERMINATED BY "|*|";

LOAD DATA LOCAL INFILE 'Bidder_uniq.dat' INTO TABLE Bidder
FIELDS TERMINATED BY "|*|";

LOAD DATA LOCAL INFILE 'Seller_uniq.dat' INTO TABLE Seller
FIELDS TERMINATED BY "|*|";